Ship UI styles
paralect/ship pull request #146
Opened 2022-07-06 07:41 UTC by aleksays

2022-07-06 15:12 UTC, Oigen43 requested changes

2022-07-06 15:13 UTC, Oigen43 commented
This PR has commits from another PRs. Please remove them.

2022-07-08 06:37 UTC, aleksays commented on services/web/next.config.js
> +const withFonts = require('next-fonts');
Cuz if u want to use font locally, u should use this plugin to correct import. Previously we used google fonts cdn

2022-07-08 08:08 UTC, Oigen43 requested changes

2022-07-08 08:08 UTC, Oigen43 commented on services/web/next.config.js
> +const withFonts = require('next-fonts');
let's remove next-fonts and use Google Fonts CDN

2022-07-08 09:32 UTC, merged