[*] Update Retool docs
paralect/ship pull request #151
Opened 2022-07-10 07:03 UTC by KuhArt

PR summary: 

- Updated retool dashdoard json. It will use only REST API queries.
- Added Retool docs.

@Oigen43 Docs static dramatically increases the repo size. Maybe it is better to add file storage and upload all docs static to it?

2022-09-07 11:15 UTC, Oigen43 commented
At the first glance looks awesome!

There are some tweaks

2022-09-07 13:21 UTC, Oigen43 requested changes

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +3. Attach resources to the Retool app. To use Retool queries you need to attach resources to them. Select the query. Click on `Resource` select input. Select an existing resource or create a new one.
3. Attach resources(API or Database) for performing Retool queries: СRUD operations with data, HTTP requests, etc. Select the query, click on `Resource` and choose one. Look at the [App Resources](#app-resources) section to see how to connect different types of resources.

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +![Add REST API](/img/api/retool/users-managment-table.png)
```suggestion

![Add REST API](/img/api/retool/users-managment-table.png)
```

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +Users Management App can be used for user administration. The main features of Users Management App are:
The application is built for user administration, it can be extended and used as internal admin panel. The main features are:

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +* It is possible to find a particular user.
You can find a particular user.

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +* You can see the user's details and apply a set of actions to the user. Actions are: `Update`, `Remove`, `Verify Email`.
You can see the user's details and apply a set of actions to the user. Default actions are: `Update`, `Remove`, `Verify Email`.

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +### Koa REST API
### REST API

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +To connect Koa REST API resource:
To connect [**API**](/docs/api/overview) service:

2022-09-07 13:21 UTC, Oigen43 commented on doc/docs/api/retool.md
> +4. Add `x-admin-key` header. The value for `x-admin-key` is stored in [koa app config](https://github.com/paralect/ship/blob/master/services/api-koa/src/config/environment/index.ts#L23).
```suggestion
4. Add `x-admin-key` header. The value for `x-admin-key` is stored [here](https://github.com/paralect/ship/blob/master/services/api-koa/src/config/environment/development.json) as `adminKey`.
```

2022-09-07 13:22 UTC, Oigen43 commented
Let's instruct how to connect MongoDB at the App Resources section

2022-09-07 13:24 UTC, Oigen43 commented
Let's instruct how to work with different environments (staging/production) and add a more detailed guide on how to connect Retool from the dev environment

2022-09-07 13:26 UTC, Oigen43 commented
Please place Retool guide in Root navigation instead of the API section.
<img width="309" alt="Screenshot 2022-09-07 at 16 25 51" src="https://user-images.githubusercontent.com/45462253/188889955-88617378-53be-4092-88aa-cddd5931912e.png">

2022-09-15 08:21 UTC, mikitasolo commented on doc/docs/api/retool.md
> +Look at [Predefined Apps](#predifined-apps) section to see available apps.
pay attention to the typo in `predifined` (should be predefined)

2022-09-23 09:44 UTC, merged