Implement dropzone for user avatar
paralect/ship pull request #157
Opened 2022-07-25 07:05 UTC by RudikAleksandr

2022-07-25 12:43 UTC, Oigen43 requested changes

2022-07-25 12:43 UTC, Oigen43 commented on services/web/src/pages/profile/components/file-upload/index.jsx
> +          {() => (
do we need this arrow function?

2022-07-25 12:46 UTC, Oigen43 commented
Pls, resolve confilct

2022-08-08 10:41 UTC, RudikAleksandr commented on services/web/src/pages/profile/components/file-upload/index.jsx
> +          {() => (
yes, doesn't work without it

2022-08-25 13:05 UTC, Oigen43 approved these changes

2022-08-25 13:05 UTC, merged