Update aws deploy docs
paralect/ship pull request #256
Opened 2024-01-08 06:55 UTC by dasiklasik

2024-01-08 11:50 UTC, fruneen requested changes

2024-01-08 11:50 UTC, fruneen commented on deploy/aws/deploy/app/api/templates/deployment.yaml
> +              name: secret_name
hmm, let's create a secret ref name dynamically:

Pass in helm upgrade command (`deploy/aws/deploy/script/src/index.js` line 56) current environment (staging/production) 

And update secret ref name using variables:
```suggestion
              name: api-{{ .Values.environment }}-secret
```

also, we need to configure ConfigMaps using (differences here: https://k21academy.com/docker-kubernetes/configmaps-secrets/#:~:text=What%20is%20the%20difference%20between,API%20keys%2C%20or%20TLS%20certificates.)

2024-01-08 11:50 UTC, fruneen commented on deploy/aws/deploy/bin/deploy-secrets.sh
> +read -p "Write WEB_URL " web_url
let's remove it, because we need to use this script for updating env variables in existing application

2024-01-10 10:44 UTC, fruneen requested changes
Amazing 🤩

2024-01-10 10:44 UTC, fruneen commented on deploy/aws/deploy/bin/deploy-secrets.sh
perfect!

Maybe we will add a log, that secret was successfully created?

2024-01-10 10:44 UTC, fruneen commented on docs/deployment/kubernetes/aws.mdx
> +## Environment variables
You can use Reusable snippets for not to duplicate info about k8s envs: https://mintlify.com/docs/content/reusable-snippets

2024-01-10 12:03 UTC, dasiklasik commented on deploy/aws/deploy/bin/deploy-secrets.sh
Commands for creating and updating secrets and configmap return logs about the result of operation (examples in screenshots)
<img width="329" alt="image" src="https://github.com/paralect/ship/assets/70663414/bd01abaa-9956-4f8c-99de-06ec6d435414">
<img width="342" alt="image" src="https://github.com/paralect/ship/assets/70663414/db5ed92b-a1fe-4483-a1de-62458d2ef16e">

2024-01-10 13:42 UTC, merged