Revitalize Storybook
paralect/ship pull request #261
Opened 2024-01-18 17:09 UTC by Tropaul322

2024-01-19 07:00 UTC, fruneen requested changes
Good job! 👏

2024-01-19 07:00 UTC, fruneen commented on template/apps/web/.storybook/preview.tsx
> +} from '@mantine/core';
```suggestion
import { MantineProvider, useMantineColorScheme } from '@mantine/core';
```

2024-01-22 11:44 UTC, Tropaul322 commented on template/apps/web/.eslintrc.js
> +  ignorePatterns: ['.eslintrc.js', '!.storybook'],
I don't know how to do it differently, but I read that eslint automatically adds .storybook to ignore and it needs to be removed from ignore using !.

2024-01-22 11:46 UTC, Tropaul322 commented on template/.github/workflows/storybook-deployment.yml
> +          token: ${{ secrets.GITHUB_TOKEN }}
If I'm not mistaken, GITHUB_TOKEN is automatically added by actions.

2024-01-22 12:03 UTC, fruneen approved these changes
Perfect!

2024-01-22 12:05 UTC, merged